{"version":"3.8.0","messages":["\nAn error occurred while loading ./spec/first_challenge_spec.rb.\n\u001b[31mFailure/Error: \u001b[0mpry.binding\u001b[0m\n\u001b[31m\u001b[0m\n\u001b[31mNoMethodError:\u001b[0m\n\u001b[31m  private method `binding' called for nil:NilClass\u001b[0m\n\u001b[31m  Did you mean?  __binding__\u001b[0m\n\u001b[36m# ./lib/first_challenge.rb:31:in `<top (required)>'\u001b[0m\n\u001b[36m# ./spec/first_challenge_spec.rb:2:in `require_relative'\u001b[0m\n\u001b[36m# ./spec/first_challenge_spec.rb:2:in `<top (required)>'\u001b[0m\n"],"examples":[],"summary":{"duration":0.000308776,"example_count":0,"failure_count":0,"pending_count":0,"errors_outside_of_examples_count":1},"summary_line":"0 examples, 0 failures, 1 error occurred outside of examples"}